// Generated by CoffeeScript 1.8.0
(function() {
  var Promise, cheerio, findLabel, findValue, headers, partialSelectFromElement, request, url;

  require("coffee-script/register");

  Promise = require("bluebird");

  request = Promise.promisify(require("request"));

  cheerio = require('cheerio');

  url = "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=179538";

  headers = {};

  partialSelectFromElement = function(selector) {
    return function(el, $) {
      return $(el).find(selector).first().html().trim();
    };
  };

  findLabel = partialSelectFromElement('div.label');

  findValue = partialSelectFromElement('div.value');

  request({
    'url': url,
    'headers': headers
  }).then(function(response) {
    return response[1];
  }).then(function(markup) {
    return cheerio.load(markup);
  }).then(function($) {
    return $('div.row').map(function(i, el) {
      var label, value;
      label = findLabel(el, $);
      value = findValue(el, $);
      return {
        'label': label,
        'value': value
      };
    }).get();
  }).then(function(cardData) {
    return console.log('card-data: ' + cardData.map(JSON.stringify).join(', '));
  }).done(function() {
    return process.exit(0);
  });

}).call(this);
