// Generated by CoffeeScript 1.8.0
(function() {
  var Promise, cheerio, findLabel, findValue, headers, partialSelectFromElement, request, url;

  require("coffee-script/register");

  Promise = require("bluebird");

  request = Promise.promisify(require("request"));

  cheerio = require('cheerio');

  url = "http://gatherer.wizards.com/Pages/Search/Default.aspx?output=compact&set=%5b%22Alara+Reborn%22%5d";

  headers = {};

  partialSelectFromElement = function(selector) {
    return function(el, $) {
      return $(el).find(selector).first().html().trim();
    };
  };

  findLabel = partialSelectFromElement('div.label');

  findValue = partialSelectFromElement('div.value');

  request({
    'url': url,
    'headers': headers
  }).then(function(response) {
    return response[1];
  }).then(function(markup) {
    return cheerio.load(markup);
  }).then(function($) {
    console.log($('table.compact .cardItem .name a').length);
    return $;
  }).then(function($) {
    return $('table.compact .cardItem .name a').map(function(i, el) {
      console.log($(el).attr('href'));
      return $(el).attr('href');
    }).get();
  }).then
      .then(function(links) {
    return console.log('links: ' + links.join(', '));
  });

}).call(this);
